services:
  brewer:
    build:
      context: .
    container_name: brewer
    ports:
      - "8082:3001"
    environment:
      PORT: 3001
    restart: unless-stopped
    volumes:
      - brewer-data:/app/.data

volumes:
  brewer-data:
